<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>OcrReview.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WeCantSpell.Hunspell" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Dictionaries\en_US.aff" />
    <EmbeddedResource Include="Dictionaries\en_US.dic" />
  </ItemGroup>

</Project>
